### ISSUE TITLE
Biome colors are not disabled according to the season

### ISSUE THREAD

**Issue by MetricsLite** [AdvancedPlugins/Seasons#199]
### Describe the bug

For example, from the biomeConfiguration file below, I do not want the biome colors to change during the summer and spring seasons in any biome.
**[]** or **“”** and the plugin will not work:

```
summer:
    # If snow is true, rain will be replaced by snow
    snow: false
    sky: []
    fog: []
    water: []
    waterFog: []
    grass: []
    tree: []
```

### How to reproduce

^^^
