### ISSUE TITLE
Support Nether & End dimensions

### ISSUE THREAD

**Issue by Mitality** [AdvancedPlugins/Seasons#37]
### Describe the feature

This should be really easy to do, as the only change needed seems to be a toggle (or even better: multiple toggles) within the biomeConfiguration to disable **seasonal mobs**, **seasonal temperature change**, **temperature change through daytime**, **weather indicaor** (maybe add a flame emoji there for nether - I'm sure you'll find something that fits for the end dimension too) and **grass/water  generation in spring** for specific biome groups. In short: Let us make biome configurations for nether and end biomes, that only use the temperature system, ty in advance!

**Comment by Mitality** [comment]
How about combining this feature with [this](https://github.com/AdvancedPlugins/Seasons/issues/52#issuecomment-1991983633)? Just add biome overrides for nether and end biomes by default and have them use a custom temperature formula too, to get rid of seasonal temperature changes. Then just add an optional flame icon for the nether and something that fits for the end dimension next to the weather-icon-configuration, and there we have not only nether and end dimension support, but also support for every custom biome you can imagine, as well as an option to disable seasonal colors said biome-temperature-overrides.

**Comment by Mitality** [comment]
You can add biomeOverrides with optional custom temperature-formulas like this:
```
biomeTemperatureOverrides:
   NETHER_WASTES: 40 "TEMP-FORMULA"
   FROZEN_OCEAN: -6
   mirage_isles: 3
```
And then add something like this for the icons:
```
icon:
    sun: "&6☀" # Shown during the day when sky is clear
    moon: "&7☽" # Shown at night when sky is clear
    rain: "&3☂" # Shown when raining
    snow: "&b✻" # Shown when snowing
    nether: "&4🔥" # Shown in the nether dimension
    end: "&7☽" # Shown in the end dimension
```

It's as easy as that, 2 issues resolved at once!
