### ISSUE TITLE
Add a setting to disable seasonal colors for certain biomes

### ISSUE THREAD

**Issue by Mitality** [AdvancedPlugins/Seasons#52]
### Describe the feature

Could even look like this:

```
# Seasonal Settings
seasons:
  spring:
    snow: false
    sky: ""
    fog: ""
    water: ""
    waterFog: ""
    grass: ""
    tree: ""

  summer:
    snow: false
    sky: ""
    fog: ""
    water: ""
    waterFog: ""  
    grass: ""
    tree: ""

  fall:
    snow: false
    sky: ""
    fog: ""
    water: ""
    waterFog: ""
    grass: ""
    tree: ""

  winter:
    winter-freeze: true
    snow: true
    sky: ""
    fog: ""
    water: ""
    waterFog: ""
    grass: ""
    tree: ""
```
