### ISSUE TITLE
Conditions for Temperature-Events

### ISSUE THREAD

**Issue by Mitality** [AdvancedPlugins/Seasons#56]
### Describe the feature

Could look like this:
```
temperatureEvents:
  freeze:
    temperature: -10
    conditions:
      - 'ARMOR:LEATHER_HELMET:FALSE'
      - 'ARMOR:LEATHER_CHESTPLATE:FALSE'
      - 'ARMOR:LEATHER_LEGGINGS:FALSE'
      - 'ARMOR:LEATHER_BOOTS:FALSE'
      - 'MAIN_HAND:TORCH:FALSE'
      - 'OFF_HAND:TORCH:FALSE'
    effects:
      - 'SCREEN_FREEZE:200'
      - 'PLAY_SOUND:BLOCK_SNOW_PLACE:1:0.2'
```
...in this example, a player would not freeze with any piece of leather-armor equipped, or a torch in hand.

Maybe also like this:
```
temperatureEvents:
  freeze:
    temperature: -10
    conditions:
      - 'ARMOR:LEATHER:FALSE'
    effects:
      - 'SCREEN_FREEZE:200'
      - 'PLAY_SOUND:BLOCK_SNOW_PLACE:1:0.2'
```
(like this, a player would have to wear full leather armor to avoid freezing)

- There's a lot more potential, feel free to show off what else you can imagine ^^
